insert into trayecto (nombre, id_estacion, id_tren) values ('Tuwiri Wetan', 21, 8);
insert into trayecto (nombre, id_estacion, id_tren) values ('Sambilawang', 6, 13);
insert into trayecto (nombre, id_estacion, id_tren) values ('Corral', 6, 3);
insert into trayecto (nombre, id_estacion, id_tren) values ('Fangtai', 12, 96);
insert into trayecto (nombre, id_estacion, id_tren) values ('Vincennes', 1, 51);
insert into trayecto (nombre, id_estacion, id_tren) values ('Foxton', 96, 98);
insert into trayecto (nombre, id_estacion, id_tren) values ('Quesada', 82, 7);
insert into trayecto (nombre, id_estacion, id_tren) values ('Almeria', 61, 45);
insert into trayecto (nombre, id_estacion, id_tren) values ('Wotan', 16, 23);
insert into trayecto (nombre, id_estacion, id_tren) values ('Rudnyy', 74, 86);
insert into trayecto (nombre, id_estacion, id_tren) values ('Bun Barat', 5, 2);
insert into trayecto (nombre, id_estacion, id_tren) values ('Shiban', 44, 33);
insert into trayecto (nombre, id_estacion, id_tren) values ('Furongqiao', 31, 56);
insert into trayecto (nombre, id_estacion, id_tren) values ('Issad', 81, 98);
insert into trayecto (nombre, id_estacion, id_tren) values ('Dawan', 40, 15);
insert into trayecto (nombre, id_estacion, id_tren) values ('Cisantri', 25, 36);
insert into trayecto (nombre, id_estacion, id_tren) values ('Tân Hòa', 11, 9);
insert into trayecto (nombre, id_estacion, id_tren) values ('Ignalina', 37, 64);
insert into trayecto (nombre, id_estacion, id_tren) values ('Pont-à-Mousson', 63, 11);
insert into trayecto (nombre, id_estacion, id_tren) values ('Tajimi', 24, 12);
insert into trayecto (nombre, id_estacion, id_tren) values ('Jacksonville', 62, 99);
insert into trayecto (nombre, id_estacion, id_tren) values ('Gavarr', 77, 79);
insert into trayecto (nombre, id_estacion, id_tren) values ('Rathnew', 20, 51);
insert into trayecto (nombre, id_estacion, id_tren) values ('Trần Văn Thời', 61, 79);
insert into trayecto (nombre, id_estacion, id_tren) values ('Matsutō', 36, 54);
insert into trayecto (nombre, id_estacion, id_tren) values ('Kulykiv', 82, 41);
insert into trayecto (nombre, id_estacion, id_tren) values ('Paris 08', 70, 69);
insert into trayecto (nombre, id_estacion, id_tren) values ('Nyuksenitsa', 23, 14);
insert into trayecto (nombre, id_estacion, id_tren) values ('Suwaru', 81, 20);
insert into trayecto (nombre, id_estacion, id_tren) values ('Veinticinco de Mayo', 26, 82);
insert into trayecto (nombre, id_estacion, id_tren) values ('Mengxi', 9, 93);
insert into trayecto (nombre, id_estacion, id_tren) values ('Huotong', 25, 49);
insert into trayecto (nombre, id_estacion, id_tren) values ('Medzhibozh', 40, 4);
insert into trayecto (nombre, id_estacion, id_tren) values ('Tambaksumur', 57, 27);
insert into trayecto (nombre, id_estacion, id_tren) values ('Thai Charoen', 100, 53);
insert into trayecto (nombre, id_estacion, id_tren) values ('Banān', 42, 30);
insert into trayecto (nombre, id_estacion, id_tren) values ('Domalanoan', 47, 90);
insert into trayecto (nombre, id_estacion, id_tren) values ('At Tawāhī', 65, 21);
insert into trayecto (nombre, id_estacion, id_tren) values ('Manolo Fortich', 51, 56);
insert into trayecto (nombre, id_estacion, id_tren) values ('Chandra', 33, 50);
insert into trayecto (nombre, id_estacion, id_tren) values ('Quxia', 85, 31);
insert into trayecto (nombre, id_estacion, id_tren) values ('Boucinha', 90, 36);
insert into trayecto (nombre, id_estacion, id_tren) values ('Açu', 61, 35);
insert into trayecto (nombre, id_estacion, id_tren) values ('Libofshë', 98, 47);
insert into trayecto (nombre, id_estacion, id_tren) values ('Sausa', 17, 39);
insert into trayecto (nombre, id_estacion, id_tren) values ('Kohila', 57, 99);
insert into trayecto (nombre, id_estacion, id_tren) values ('Nanyo', 45, 67);
insert into trayecto (nombre, id_estacion, id_tren) values ('Diriomo', 38, 32);
insert into trayecto (nombre, id_estacion, id_tren) values ('Meipu', 19, 16);
insert into trayecto (nombre, id_estacion, id_tren) values ('Santo Tomé', 100, 71);
insert into trayecto (nombre, id_estacion, id_tren) values ('Shuijiang', 9, 7);
insert into trayecto (nombre, id_estacion, id_tren) values ('Qujing', 84, 40);
insert into trayecto (nombre, id_estacion, id_tren) values ('Nonoichi', 74, 28);
insert into trayecto (nombre, id_estacion, id_tren) values ('Yujiawu', 11, 92);
insert into trayecto (nombre, id_estacion, id_tren) values ('Ylämaa', 84, 67);
insert into trayecto (nombre, id_estacion, id_tren) values ('Matadi', 98, 9);
insert into trayecto (nombre, id_estacion, id_tren) values ('Chonogol', 50, 28);
insert into trayecto (nombre, id_estacion, id_tren) values ('Malysheva', 61, 30);
insert into trayecto (nombre, id_estacion, id_tren) values ('Krajan Timur Suger Kidul', 6, 58);
insert into trayecto (nombre, id_estacion, id_tren) values ('Baton Rouge', 36, 15);
insert into trayecto (nombre, id_estacion, id_tren) values ('Duntou', 69, 25);
insert into trayecto (nombre, id_estacion, id_tren) values ('Fajões', 36, 13);
insert into trayecto (nombre, id_estacion, id_tren) values ('Tabuc Pontevedra', 47, 72);
insert into trayecto (nombre, id_estacion, id_tren) values ('Burgersfort', 10, 88);
insert into trayecto (nombre, id_estacion, id_tren) values ('Qiaoxi', 41, 1);
insert into trayecto (nombre, id_estacion, id_tren) values ('Redondos', 60, 87);
insert into trayecto (nombre, id_estacion, id_tren) values ('Zhongzhai', 91, 52);
insert into trayecto (nombre, id_estacion, id_tren) values ('Kadukaung', 88, 7);
insert into trayecto (nombre, id_estacion, id_tren) values ('Bender', 78, 34);
insert into trayecto (nombre, id_estacion, id_tren) values ('Belén', 65, 15);
insert into trayecto (nombre, id_estacion, id_tren) values ('Zaozerne', 91, 86);
insert into trayecto (nombre, id_estacion, id_tren) values ('Al Ma‘baţlī', 83, 17);
insert into trayecto (nombre, id_estacion, id_tren) values ('Santa Isabel', 93, 88);
insert into trayecto (nombre, id_estacion, id_tren) values ('Dongxiang', 50, 35);
insert into trayecto (nombre, id_estacion, id_tren) values ('Matou', 41, 72);
insert into trayecto (nombre, id_estacion, id_tren) values ('Tagiura', 11, 81);
insert into trayecto (nombre, id_estacion, id_tren) values ('Tilburg', 60, 12);
insert into trayecto (nombre, id_estacion, id_tren) values ('Dumalneg', 1, 90);
insert into trayecto (nombre, id_estacion, id_tren) values ('Dongdajie', 31, 52);
insert into trayecto (nombre, id_estacion, id_tren) values ('Zhetang', 95, 33);
insert into trayecto (nombre, id_estacion, id_tren) values ('Américo Brasiliense', 46, 63);
insert into trayecto (nombre, id_estacion, id_tren) values ('Quỳnh Côi', 46, 15);
insert into trayecto (nombre, id_estacion, id_tren) values ('Shuangmiao', 41, 36);
insert into trayecto (nombre, id_estacion, id_tren) values ('Kněžpole', 24, 32);
insert into trayecto (nombre, id_estacion, id_tren) values ('Ristinummi', 85, 53);
insert into trayecto (nombre, id_estacion, id_tren) values ('Guanchi', 50, 69);
insert into trayecto (nombre, id_estacion, id_tren) values ('Burns Lake', 60, 9);
insert into trayecto (nombre, id_estacion, id_tren) values ('Gulrip’shi', 93, 63);
insert into trayecto (nombre, id_estacion, id_tren) values ('Lenger', 15, 93);
insert into trayecto (nombre, id_estacion, id_tren) values ('Xingquan', 71, 63);
insert into trayecto (nombre, id_estacion, id_tren) values ('Wawer', 64, 59);
insert into trayecto (nombre, id_estacion, id_tren) values ('Kuressaare', 74, 39);
insert into trayecto (nombre, id_estacion, id_tren) values ('Masindi', 42, 16);
insert into trayecto (nombre, id_estacion, id_tren) values ('Fuming', 51, 55);
insert into trayecto (nombre, id_estacion, id_tren) values ('Parapat', 31, 23);
insert into trayecto (nombre, id_estacion, id_tren) values ('Dos Hermanas', 6, 54);
insert into trayecto (nombre, id_estacion, id_tren) values ('Amānzī', 86, 56);
insert into trayecto (nombre, id_estacion, id_tren) values ('Pau', 77, 100);
insert into trayecto (nombre, id_estacion, id_tren) values ('Fayaoué', 42, 58);
insert into trayecto (nombre, id_estacion, id_tren) values ('Novo-Peredelkino', 56, 3);
