insert into tren (modelo, capacidad) values ('LTD Crown Victoria', 44);
insert into tren (modelo, capacidad) values ('G-Series G30', 43);
insert into tren (modelo, capacidad) values ('530', 38);
insert into tren (modelo, capacidad) values ('Continental', 36);
insert into tren (modelo, capacidad) values ('550', 29);
insert into tren (modelo, capacidad) values ('S40', 33);
insert into tren (modelo, capacidad) values ('525', 37);
insert into tren (modelo, capacidad) values ('Discovery', 47);
insert into tren (modelo, capacidad) values ('V70', 47);
insert into tren (modelo, capacidad) values ('MR2', 28);
insert into tren (modelo, capacidad) values ('Uplander', 50);
insert into tren (modelo, capacidad) values ('Intrepid', 31);
insert into tren (modelo, capacidad) values ('9-5', 30);
insert into tren (modelo, capacidad) values ('Galant', 40);
insert into tren (modelo, capacidad) values ('Element', 36);
insert into tren (modelo, capacidad) values ('Jetta', 34);
insert into tren (modelo, capacidad) values ('Villager', 44);
insert into tren (modelo, capacidad) values ('Express 2500', 44);
insert into tren (modelo, capacidad) values ('S-Class', 48);
insert into tren (modelo, capacidad) values ('Grand Prix', 20);
insert into tren (modelo, capacidad) values ('Scirocco', 48);
insert into tren (modelo, capacidad) values ('Insight', 29);
insert into tren (modelo, capacidad) values ('Enclave', 50);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 47);
insert into tren (modelo, capacidad) values ('Blazer', 32);
insert into tren (modelo, capacidad) values ('New Beetle', 48);
insert into tren (modelo, capacidad) values ('LTD Crown Victoria', 37);
insert into tren (modelo, capacidad) values ('300SL', 22);
insert into tren (modelo, capacidad) values ('Ranger', 28);
insert into tren (modelo, capacidad) values ('Express 1500', 33);
insert into tren (modelo, capacidad) values ('Caravan', 25);
insert into tren (modelo, capacidad) values ('Aspen', 36);
insert into tren (modelo, capacidad) values ('Sky', 28);
insert into tren (modelo, capacidad) values ('Escalade EXT', 26);
insert into tren (modelo, capacidad) values ('Outback', 21);
insert into tren (modelo, capacidad) values ('A6', 31);
insert into tren (modelo, capacidad) values ('626', 39);
insert into tren (modelo, capacidad) values ('Pajero', 29);
insert into tren (modelo, capacidad) values ('Accord', 40);
insert into tren (modelo, capacidad) values ('V70', 44);
insert into tren (modelo, capacidad) values ('Grand Voyager', 37);
insert into tren (modelo, capacidad) values ('Achieva', 46);
insert into tren (modelo, capacidad) values ('3500', 43);
insert into tren (modelo, capacidad) values ('E-Class', 31);
insert into tren (modelo, capacidad) values ('Eclipse', 29);
insert into tren (modelo, capacidad) values ('ES', 29);
insert into tren (modelo, capacidad) values ('Camry', 36);
insert into tren (modelo, capacidad) values ('Cabriolet', 27);
insert into tren (modelo, capacidad) values ('CL65 AMG', 39);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 40);
insert into tren (modelo, capacidad) values ('Econoline E250', 48);
insert into tren (modelo, capacidad) values ('Sierra', 22);
insert into tren (modelo, capacidad) values ('Discovery', 30);
insert into tren (modelo, capacidad) values ('Quattro', 41);
insert into tren (modelo, capacidad) values ('Sierra 1500', 27);
insert into tren (modelo, capacidad) values ('911', 38);
insert into tren (modelo, capacidad) values ('Tacoma Xtra', 23);
insert into tren (modelo, capacidad) values ('Viper', 21);
insert into tren (modelo, capacidad) values ('944', 39);
insert into tren (modelo, capacidad) values ('SVX', 48);
insert into tren (modelo, capacidad) values ('Escalade ESV', 38);
insert into tren (modelo, capacidad) values ('W201', 28);
insert into tren (modelo, capacidad) values ('599 GTB Fiorano', 25);
insert into tren (modelo, capacidad) values ('Sonoma', 29);
insert into tren (modelo, capacidad) values ('S80', 48);
insert into tren (modelo, capacidad) values ('RL', 31);
insert into tren (modelo, capacidad) values ('D150 Club', 30);
insert into tren (modelo, capacidad) values ('Jimmy', 41);
insert into tren (modelo, capacidad) values ('Lancer', 43);
insert into tren (modelo, capacidad) values ('Verona', 28);
insert into tren (modelo, capacidad) values ('H3T', 48);
insert into tren (modelo, capacidad) values ('Vibe', 27);
insert into tren (modelo, capacidad) values ('Tundra', 39);
insert into tren (modelo, capacidad) values ('F250', 47);
insert into tren (modelo, capacidad) values ('Suburban 1500', 27);
insert into tren (modelo, capacidad) values ('FX', 24);
insert into tren (modelo, capacidad) values ('Yukon XL 1500', 37);
insert into tren (modelo, capacidad) values ('Econoline E250', 29);
insert into tren (modelo, capacidad) values ('V50', 34);
insert into tren (modelo, capacidad) values ('300ZX', 36);
insert into tren (modelo, capacidad) values ('Sportage', 37);
insert into tren (modelo, capacidad) values ('Forte', 47);
insert into tren (modelo, capacidad) values ('M3', 21);
insert into tren (modelo, capacidad) values ('Magnum', 31);
insert into tren (modelo, capacidad) values ('760', 29);
insert into tren (modelo, capacidad) values ('Diamante', 37);
insert into tren (modelo, capacidad) values ('F250', 48);
insert into tren (modelo, capacidad) values ('Fox', 45);
insert into tren (modelo, capacidad) values ('Tahoe', 36);
insert into tren (modelo, capacidad) values ('Q7', 23);
insert into tren (modelo, capacidad) values ('Cougar', 22);
insert into tren (modelo, capacidad) values ('Grand Prix', 31);
insert into tren (modelo, capacidad) values ('Nubira', 45);
insert into tren (modelo, capacidad) values ('Cavalier', 37);
insert into tren (modelo, capacidad) values ('Concorde', 50);
insert into tren (modelo, capacidad) values ('Contour', 23);
insert into tren (modelo, capacidad) values ('Cultus', 47);
insert into tren (modelo, capacidad) values ('Sixty Special', 30);
insert into tren (modelo, capacidad) values ('F-Series', 46);
insert into tren (modelo, capacidad) values ('Biturbo', 35);
insert into tren (modelo, capacidad) values ('Frontier', 42);
insert into tren (modelo, capacidad) values ('S10 Blazer', 20);
insert into tren (modelo, capacidad) values ('Mariner', 26);
insert into tren (modelo, capacidad) values ('Corsica', 42);
insert into tren (modelo, capacidad) values ('Phantom', 45);
insert into tren (modelo, capacidad) values ('Mustang', 36);
insert into tren (modelo, capacidad) values ('S-Class', 45);
insert into tren (modelo, capacidad) values ('IS-F', 38);
insert into tren (modelo, capacidad) values ('Econoline E350', 38);
insert into tren (modelo, capacidad) values ('Silverado 2500', 32);
insert into tren (modelo, capacidad) values ('Starion', 30);
insert into tren (modelo, capacidad) values ('Town Car', 35);
insert into tren (modelo, capacidad) values ('Edge', 23);
insert into tren (modelo, capacidad) values ('Grand Prix', 33);
insert into tren (modelo, capacidad) values ('X5', 30);
insert into tren (modelo, capacidad) values ('Tacoma Xtra', 46);
insert into tren (modelo, capacidad) values ('F350', 42);
insert into tren (modelo, capacidad) values ('Accord', 43);
insert into tren (modelo, capacidad) values ('3 Series', 27);
insert into tren (modelo, capacidad) values ('Regal', 28);
insert into tren (modelo, capacidad) values ('XJ Series', 21);
insert into tren (modelo, capacidad) values ('Rodeo', 44);
insert into tren (modelo, capacidad) values ('Wrangler', 49);
insert into tren (modelo, capacidad) values ('Catera', 38);
insert into tren (modelo, capacidad) values ('9-3', 47);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 47);
insert into tren (modelo, capacidad) values ('Passat', 26);
insert into tren (modelo, capacidad) values ('M-Class', 48);
insert into tren (modelo, capacidad) values ('RS 4', 48);
insert into tren (modelo, capacidad) values ('J', 35);
insert into tren (modelo, capacidad) values ('GS', 21);
insert into tren (modelo, capacidad) values ('Q7', 41);
insert into tren (modelo, capacidad) values ('Avenger', 49);
insert into tren (modelo, capacidad) values ('Avenger', 44);
insert into tren (modelo, capacidad) values ('S10', 26);
insert into tren (modelo, capacidad) values ('Silverado 3500HD', 49);
insert into tren (modelo, capacidad) values ('E350', 34);
insert into tren (modelo, capacidad) values ('Grand Prix', 37);
insert into tren (modelo, capacidad) values ('A6', 23);
insert into tren (modelo, capacidad) values ('Cobalt', 21);
insert into tren (modelo, capacidad) values ('Corsica', 21);
insert into tren (modelo, capacidad) values ('Land Cruiser', 22);
insert into tren (modelo, capacidad) values ('Town Car', 35);
insert into tren (modelo, capacidad) values ('Silverado 3500', 43);
insert into tren (modelo, capacidad) values ('Relay', 20);
insert into tren (modelo, capacidad) values ('ES', 24);
insert into tren (modelo, capacidad) values ('Monte Carlo', 29);
insert into tren (modelo, capacidad) values ('C70', 25);
insert into tren (modelo, capacidad) values ('Acclaim', 27);
insert into tren (modelo, capacidad) values ('370Z', 47);
insert into tren (modelo, capacidad) values ('CL-Class', 30);
insert into tren (modelo, capacidad) values ('New Beetle', 50);
insert into tren (modelo, capacidad) values ('Mirage', 42);
insert into tren (modelo, capacidad) values ('M6', 48);
insert into tren (modelo, capacidad) values ('Sequoia', 31);
insert into tren (modelo, capacidad) values ('MDX', 22);
insert into tren (modelo, capacidad) values ('VUE', 26);
insert into tren (modelo, capacidad) values ('S10 Blazer', 46);
insert into tren (modelo, capacidad) values ('Beretta', 25);
insert into tren (modelo, capacidad) values ('F-Series', 35);
insert into tren (modelo, capacidad) values ('Prowler', 36);
insert into tren (modelo, capacidad) values ('GTO', 38);
insert into tren (modelo, capacidad) values ('Lumina APV', 47);
insert into tren (modelo, capacidad) values ('G35', 38);
insert into tren (modelo, capacidad) values ('Tahoe', 41);
insert into tren (modelo, capacidad) values ('Genesis Coupe', 30);
insert into tren (modelo, capacidad) values ('Ram 2500', 44);
insert into tren (modelo, capacidad) values ('Thunderbird', 31);
insert into tren (modelo, capacidad) values ('Probe', 37);
insert into tren (modelo, capacidad) values ('Freestar', 44);
insert into tren (modelo, capacidad) values ('Impala', 38);
insert into tren (modelo, capacidad) values ('Sonoma Club Coupe', 30);
insert into tren (modelo, capacidad) values ('Sonata', 39);
insert into tren (modelo, capacidad) values ('MKT', 47);
insert into tren (modelo, capacidad) values ('Aurora', 27);
insert into tren (modelo, capacidad) values ('Pajero', 29);
insert into tren (modelo, capacidad) values ('M-Class', 43);
insert into tren (modelo, capacidad) values ('5 Series', 45);
insert into tren (modelo, capacidad) values ('Quattroporte', 44);
insert into tren (modelo, capacidad) values ('Vandura G3500', 20);
insert into tren (modelo, capacidad) values ('Sierra 1500', 20);
insert into tren (modelo, capacidad) values ('GLK-Class', 24);
insert into tren (modelo, capacidad) values ('Fifth Ave', 30);
insert into tren (modelo, capacidad) values ('Accord', 30);
insert into tren (modelo, capacidad) values ('Vandura 1500', 22);
insert into tren (modelo, capacidad) values ('Caliber', 25);
insert into tren (modelo, capacidad) values ('Monte Carlo', 26);
insert into tren (modelo, capacidad) values ('EXP', 46);
insert into tren (modelo, capacidad) values ('Malibu', 37);
insert into tren (modelo, capacidad) values ('Eurovan', 37);
insert into tren (modelo, capacidad) values ('H2', 30);
insert into tren (modelo, capacidad) values ('240SX', 43);
insert into tren (modelo, capacidad) values ('Jimmy', 47);
insert into tren (modelo, capacidad) values ('Malibu', 23);
insert into tren (modelo, capacidad) values ('Dakota Club', 36);
insert into tren (modelo, capacidad) values ('XF', 29);
insert into tren (modelo, capacidad) values ('Camry Solara', 48);
insert into tren (modelo, capacidad) values ('Roadmaster', 46);
insert into tren (modelo, capacidad) values ('Z8', 31);
insert into tren (modelo, capacidad) values ('Camaro', 22);
insert into tren (modelo, capacidad) values ('Camaro', 23);
insert into tren (modelo, capacidad) values ('Corolla', 44);
insert into tren (modelo, capacidad) values ('Safari', 46);
insert into tren (modelo, capacidad) values ('Ram Wagon B350', 43);
insert into tren (modelo, capacidad) values ('900', 41);
insert into tren (modelo, capacidad) values ('Spyder', 43);
insert into tren (modelo, capacidad) values ('Forester', 22);
insert into tren (modelo, capacidad) values ('GS', 24);
insert into tren (modelo, capacidad) values ('Mirage', 24);
insert into tren (modelo, capacidad) values ('MX-5', 22);
insert into tren (modelo, capacidad) values ('Outback', 23);
insert into tren (modelo, capacidad) values ('Golf III', 50);
insert into tren (modelo, capacidad) values ('Skylark', 45);
insert into tren (modelo, capacidad) values ('Sprinter', 26);
insert into tren (modelo, capacidad) values ('Laser', 25);
insert into tren (modelo, capacidad) values ('GTI', 28);
insert into tren (modelo, capacidad) values ('Spider', 37);
insert into tren (modelo, capacidad) values ('CR-V', 31);
insert into tren (modelo, capacidad) values ('Quest', 46);
insert into tren (modelo, capacidad) values ('Liberty', 45);
insert into tren (modelo, capacidad) values ('Routan', 44);
insert into tren (modelo, capacidad) values ('4Runner', 24);
insert into tren (modelo, capacidad) values ('E-Class', 40);
insert into tren (modelo, capacidad) values ('740', 35);
insert into tren (modelo, capacidad) values ('Impreza', 45);
insert into tren (modelo, capacidad) values ('MPV', 43);
insert into tren (modelo, capacidad) values ('Prius', 50);
insert into tren (modelo, capacidad) values ('E250', 26);
insert into tren (modelo, capacidad) values ('A6', 29);
insert into tren (modelo, capacidad) values ('S2000', 45);
insert into tren (modelo, capacidad) values ('2CV', 48);
insert into tren (modelo, capacidad) values ('Maxima', 30);
insert into tren (modelo, capacidad) values ('Jetta III', 34);
insert into tren (modelo, capacidad) values ('525', 43);
insert into tren (modelo, capacidad) values ('A4', 43);
insert into tren (modelo, capacidad) values ('300ZX', 37);
insert into tren (modelo, capacidad) values ('Dakota Club', 46);
insert into tren (modelo, capacidad) values ('Mighty Max', 34);
insert into tren (modelo, capacidad) values ('i-370', 34);
insert into tren (modelo, capacidad) values ('Camaro', 30);
insert into tren (modelo, capacidad) values ('3 Series', 22);
insert into tren (modelo, capacidad) values ('LX', 22);
insert into tren (modelo, capacidad) values ('Santa Fe', 47);
insert into tren (modelo, capacidad) values ('4Runner', 37);
insert into tren (modelo, capacidad) values ('Colt', 48);
insert into tren (modelo, capacidad) values ('RAV4', 42);
insert into tren (modelo, capacidad) values ('C-Class', 29);
insert into tren (modelo, capacidad) values ('Starion', 29);
insert into tren (modelo, capacidad) values ('XK', 50);
insert into tren (modelo, capacidad) values ('GTI', 35);
insert into tren (modelo, capacidad) values ('Land Cruiser', 37);
insert into tren (modelo, capacidad) values ('Sonata', 43);
insert into tren (modelo, capacidad) values ('Turbo Firefly', 22);
insert into tren (modelo, capacidad) values ('Sunfire', 26);
insert into tren (modelo, capacidad) values ('Legacy', 20);
insert into tren (modelo, capacidad) values ('Mustang', 46);
insert into tren (modelo, capacidad) values ('Q5', 36);
insert into tren (modelo, capacidad) values ('G25', 26);
insert into tren (modelo, capacidad) values ('W201', 38);
insert into tren (modelo, capacidad) values ('Lucerne', 25);
insert into tren (modelo, capacidad) values ('RX-7', 28);
insert into tren (modelo, capacidad) values ('3500 Club Coupe', 34);
insert into tren (modelo, capacidad) values ('Electra', 23);
insert into tren (modelo, capacidad) values ('Sidekick', 31);
insert into tren (modelo, capacidad) values ('Thunderbird', 21);
insert into tren (modelo, capacidad) values ('Equator', 31);
insert into tren (modelo, capacidad) values ('Dakota Club', 29);
insert into tren (modelo, capacidad) values ('Suburban 1500', 42);
insert into tren (modelo, capacidad) values ('Montero', 22);
insert into tren (modelo, capacidad) values ('Colt Vista', 39);
insert into tren (modelo, capacidad) values ('Esprit', 42);
insert into tren (modelo, capacidad) values ('Hombre Space', 46);
insert into tren (modelo, capacidad) values ('Escort', 50);
insert into tren (modelo, capacidad) values ('Eclipse', 41);
insert into tren (modelo, capacidad) values ('Exige', 23);
insert into tren (modelo, capacidad) values ('Continental', 45);
insert into tren (modelo, capacidad) values ('Rondo', 34);
insert into tren (modelo, capacidad) values ('Corolla', 50);
insert into tren (modelo, capacidad) values ('Esprit', 27);
insert into tren (modelo, capacidad) values ('Corvair', 47);
insert into tren (modelo, capacidad) values ('Pathfinder', 42);
insert into tren (modelo, capacidad) values ('T100 Xtra', 42);
insert into tren (modelo, capacidad) values ('Grand Prix', 39);
insert into tren (modelo, capacidad) values ('Arnage', 26);
insert into tren (modelo, capacidad) values ('GTI', 34);
insert into tren (modelo, capacidad) values ('GS', 24);
insert into tren (modelo, capacidad) values ('Savana 1500', 27);
insert into tren (modelo, capacidad) values ('Envoy XUV', 48);
insert into tren (modelo, capacidad) values ('TundraMax', 33);
insert into tren (modelo, capacidad) values ('Chariot', 29);
insert into tren (modelo, capacidad) values ('Sorento', 49);
insert into tren (modelo, capacidad) values ('626', 25);
insert into tren (modelo, capacidad) values ('3500', 29);
insert into tren (modelo, capacidad) values ('Ion', 21);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 40);
insert into tren (modelo, capacidad) values ('C8 Spyder', 34);
insert into tren (modelo, capacidad) values ('Mountaineer', 30);
insert into tren (modelo, capacidad) values ('Silverado 2500', 31);
insert into tren (modelo, capacidad) values ('Montero Sport', 34);
insert into tren (modelo, capacidad) values ('XT', 27);
insert into tren (modelo, capacidad) values ('Cayenne', 25);
insert into tren (modelo, capacidad) values ('SJ 410', 41);
insert into tren (modelo, capacidad) values ('Edge', 38);
insert into tren (modelo, capacidad) values ('Savana 1500', 24);
insert into tren (modelo, capacidad) values ('CR-V', 39);
insert into tren (modelo, capacidad) values ('Sportage', 37);
insert into tren (modelo, capacidad) values ('SL-Class', 45);
insert into tren (modelo, capacidad) values ('Galant', 46);
insert into tren (modelo, capacidad) values ('Century', 48);
insert into tren (modelo, capacidad) values ('Tiburon', 48);
insert into tren (modelo, capacidad) values ('Grand Am', 26);
insert into tren (modelo, capacidad) values ('Land Cruiser', 26);
insert into tren (modelo, capacidad) values ('Impreza', 39);
insert into tren (modelo, capacidad) values ('EXP', 23);
insert into tren (modelo, capacidad) values ('Skylark', 28);
insert into tren (modelo, capacidad) values ('MX-5', 20);
insert into tren (modelo, capacidad) values ('Caravan', 36);
insert into tren (modelo, capacidad) values ('Concorde', 29);
insert into tren (modelo, capacidad) values ('G5', 28);
insert into tren (modelo, capacidad) values ('Ghost', 27);
insert into tren (modelo, capacidad) values ('LS', 46);
insert into tren (modelo, capacidad) values ('W201', 45);
insert into tren (modelo, capacidad) values ('Challenger', 21);
insert into tren (modelo, capacidad) values ('Celica', 27);
insert into tren (modelo, capacidad) values ('LSS', 50);
insert into tren (modelo, capacidad) values ('760', 41);
insert into tren (modelo, capacidad) values ('Ram Van 2500', 30);
insert into tren (modelo, capacidad) values ('Axiom', 26);
insert into tren (modelo, capacidad) values ('Elise', 49);
insert into tren (modelo, capacidad) values ('LeSabre', 24);
insert into tren (modelo, capacidad) values ('Ram Wagon B150', 28);
insert into tren (modelo, capacidad) values ('Ranger', 25);
insert into tren (modelo, capacidad) values ('Bonneville', 27);
insert into tren (modelo, capacidad) values ('Safari', 33);
insert into tren (modelo, capacidad) values ('Voyager', 35);
insert into tren (modelo, capacidad) values ('NSX', 41);
insert into tren (modelo, capacidad) values ('Defender', 50);
insert into tren (modelo, capacidad) values ('F-Series Super Duty', 28);
insert into tren (modelo, capacidad) values ('Escape', 48);
insert into tren (modelo, capacidad) values ('Q', 32);
insert into tren (modelo, capacidad) values ('S2000', 47);
insert into tren (modelo, capacidad) values ('Grand Vitara', 29);
insert into tren (modelo, capacidad) values ('GX', 44);
insert into tren (modelo, capacidad) values ('Aura', 44);
insert into tren (modelo, capacidad) values ('Montero', 26);
insert into tren (modelo, capacidad) values ('Silverado 1500', 47);
insert into tren (modelo, capacidad) values ('Thunderbird', 24);
insert into tren (modelo, capacidad) values ('Taurus', 48);
insert into tren (modelo, capacidad) values ('Escort', 27);
insert into tren (modelo, capacidad) values ('4Runner', 46);
insert into tren (modelo, capacidad) values ('960', 25);
insert into tren (modelo, capacidad) values ('F430', 33);
insert into tren (modelo, capacidad) values ('Touareg', 43);
insert into tren (modelo, capacidad) values ('Sentra', 34);
insert into tren (modelo, capacidad) values ('Avenger', 21);
insert into tren (modelo, capacidad) values ('Fusion', 46);
insert into tren (modelo, capacidad) values ('Protege5', 20);
insert into tren (modelo, capacidad) values ('NV3500', 32);
insert into tren (modelo, capacidad) values ('Tercel', 21);
insert into tren (modelo, capacidad) values ('New Yorker', 43);
insert into tren (modelo, capacidad) values ('Aventador', 34);
insert into tren (modelo, capacidad) values ('940', 34);
insert into tren (modelo, capacidad) values ('A4', 34);
insert into tren (modelo, capacidad) values ('Skylark', 45);
insert into tren (modelo, capacidad) values ('Grand Caravan', 46);
insert into tren (modelo, capacidad) values ('Touareg', 41);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 40);
insert into tren (modelo, capacidad) values ('LS', 50);
insert into tren (modelo, capacidad) values ('Sonoma', 26);
insert into tren (modelo, capacidad) values ('Express 3500', 49);
insert into tren (modelo, capacidad) values ('Esperante', 29);
insert into tren (modelo, capacidad) values ('Sidekick', 40);
insert into tren (modelo, capacidad) values ('Mazda6', 32);
insert into tren (modelo, capacidad) values ('Santa Fe', 33);
insert into tren (modelo, capacidad) values ('S6', 45);
insert into tren (modelo, capacidad) values ('GTI', 46);
insert into tren (modelo, capacidad) values ('Ram Van 1500', 27);
insert into tren (modelo, capacidad) values ('7 Series', 23);
insert into tren (modelo, capacidad) values ('del Sol', 49);
insert into tren (modelo, capacidad) values ('Villager', 48);
insert into tren (modelo, capacidad) values ('Esperante', 29);
insert into tren (modelo, capacidad) values ('Viper', 30);
insert into tren (modelo, capacidad) values ('ES', 41);
insert into tren (modelo, capacidad) values ('Sienna', 27);
insert into tren (modelo, capacidad) values ('RX-8', 40);
insert into tren (modelo, capacidad) values ('Murciélago', 22);
insert into tren (modelo, capacidad) values ('Vanquish S', 38);
insert into tren (modelo, capacidad) values ('Discovery', 34);
insert into tren (modelo, capacidad) values ('CR-V', 28);
insert into tren (modelo, capacidad) values ('57S', 48);
insert into tren (modelo, capacidad) values ('F-Series', 36);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 37);
insert into tren (modelo, capacidad) values ('Truck', 50);
insert into tren (modelo, capacidad) values ('Tracker', 27);
insert into tren (modelo, capacidad) values ('3500', 22);
insert into tren (modelo, capacidad) values ('Trans Sport', 44);
insert into tren (modelo, capacidad) values ('Continental Mark VII', 49);
insert into tren (modelo, capacidad) values ('Crown Victoria', 48);
insert into tren (modelo, capacidad) values ('Ram', 27);
insert into tren (modelo, capacidad) values ('Mirage', 27);
insert into tren (modelo, capacidad) values ('Insight', 43);
insert into tren (modelo, capacidad) values ('Bonneville', 32);
insert into tren (modelo, capacidad) values ('D150 Club', 25);
insert into tren (modelo, capacidad) values ('QX', 36);
insert into tren (modelo, capacidad) values ('Galant', 20);
insert into tren (modelo, capacidad) values ('B-Series', 26);
insert into tren (modelo, capacidad) values ('H2', 44);
insert into tren (modelo, capacidad) values ('Diablo', 46);
insert into tren (modelo, capacidad) values ('Legacy', 49);
insert into tren (modelo, capacidad) values ('Estate', 41);
insert into tren (modelo, capacidad) values ('Parisienne', 30);
insert into tren (modelo, capacidad) values ('Legend', 49);
insert into tren (modelo, capacidad) values ('Navajo', 50);
insert into tren (modelo, capacidad) values ('Sebring', 32);
insert into tren (modelo, capacidad) values ('Quest', 37);
insert into tren (modelo, capacidad) values ('Town & Country', 23);
insert into tren (modelo, capacidad) values ('CX-9', 24);
insert into tren (modelo, capacidad) values ('V50', 24);
insert into tren (modelo, capacidad) values ('Aspire', 38);
insert into tren (modelo, capacidad) values ('RSX', 30);
insert into tren (modelo, capacidad) values ('Integra', 28);
insert into tren (modelo, capacidad) values ('Beetle', 38);
insert into tren (modelo, capacidad) values ('Coachbuilder', 27);
insert into tren (modelo, capacidad) values ('Mark VIII', 43);
insert into tren (modelo, capacidad) values ('V8 Vantage', 31);
insert into tren (modelo, capacidad) values ('Hombre', 49);
insert into tren (modelo, capacidad) values ('Skylark', 39);
insert into tren (modelo, capacidad) values ('Topaz', 25);
insert into tren (modelo, capacidad) values ('XC70', 20);
insert into tren (modelo, capacidad) values ('M', 39);
insert into tren (modelo, capacidad) values ('DeVille', 28);
insert into tren (modelo, capacidad) values ('Viper', 22);
insert into tren (modelo, capacidad) values ('Ram Van 1500', 29);
insert into tren (modelo, capacidad) values ('Model S', 28);
insert into tren (modelo, capacidad) values ('Cutlass Supreme', 36);
insert into tren (modelo, capacidad) values ('Mazda3', 24);
insert into tren (modelo, capacidad) values ('SL-Class', 25);
insert into tren (modelo, capacidad) values ('Grand Voyager', 42);
insert into tren (modelo, capacidad) values ('Corvette', 34);
insert into tren (modelo, capacidad) values ('Titan', 28);
insert into tren (modelo, capacidad) values ('5 Series', 46);
insert into tren (modelo, capacidad) values ('xB', 39);
insert into tren (modelo, capacidad) values ('Sonata', 46);
insert into tren (modelo, capacidad) values ('SJ', 25);
insert into tren (modelo, capacidad) values ('944', 40);
insert into tren (modelo, capacidad) values ('Th!nk', 46);
insert into tren (modelo, capacidad) values ('Grand Marquis', 44);
insert into tren (modelo, capacidad) values ('Continental Flying Spur', 21);
insert into tren (modelo, capacidad) values ('Sportage', 22);
insert into tren (modelo, capacidad) values ('Stealth', 34);
insert into tren (modelo, capacidad) values ('Taurus', 27);
insert into tren (modelo, capacidad) values ('Daytona', 23);
insert into tren (modelo, capacidad) values ('Mazdaspeed 3', 48);
insert into tren (modelo, capacidad) values ('DB9', 26);
insert into tren (modelo, capacidad) values ('Tundra', 30);
insert into tren (modelo, capacidad) values ('Edge', 48);
insert into tren (modelo, capacidad) values ('Lumina', 20);
insert into tren (modelo, capacidad) values ('Traverse', 20);
insert into tren (modelo, capacidad) values ('CX-7', 43);
insert into tren (modelo, capacidad) values ('9000', 31);
insert into tren (modelo, capacidad) values ('S10', 37);
insert into tren (modelo, capacidad) values ('928', 43);
insert into tren (modelo, capacidad) values ('Q', 42);
insert into tren (modelo, capacidad) values ('Savana 3500', 48);
insert into tren (modelo, capacidad) values ('Accord', 20);
insert into tren (modelo, capacidad) values ('Shadow', 38);
insert into tren (modelo, capacidad) values ('4Runner', 32);
insert into tren (modelo, capacidad) values ('S80', 20);
insert into tren (modelo, capacidad) values ('F-Series', 22);
insert into tren (modelo, capacidad) values ('Sierra 1500', 20);
insert into tren (modelo, capacidad) values ('Tundra', 33);
insert into tren (modelo, capacidad) values ('Maxima', 50);
insert into tren (modelo, capacidad) values ('Golf', 29);
insert into tren (modelo, capacidad) values ('5 Series', 50);
insert into tren (modelo, capacidad) values ('Ram 2500', 32);
insert into tren (modelo, capacidad) values ('Escape', 41);
insert into tren (modelo, capacidad) values ('B-Series Plus', 26);
insert into tren (modelo, capacidad) values ('Sorento', 40);
insert into tren (modelo, capacidad) values ('NX', 33);
insert into tren (modelo, capacidad) values ('Town & Country', 31);
insert into tren (modelo, capacidad) values ('Sonata', 30);
insert into tren (modelo, capacidad) values ('Traverse', 42);
insert into tren (modelo, capacidad) values ('G-Series 1500', 31);
insert into tren (modelo, capacidad) values ('ES', 36);
insert into tren (modelo, capacidad) values ('Lumina', 38);
insert into tren (modelo, capacidad) values ('Quattroporte', 26);
insert into tren (modelo, capacidad) values ('Grand Marquis', 23);
insert into tren (modelo, capacidad) values ('Veloster', 20);
insert into tren (modelo, capacidad) values ('Avalanche', 20);
insert into tren (modelo, capacidad) values ('Corolla', 21);
insert into tren (modelo, capacidad) values ('300SE', 44);
insert into tren (modelo, capacidad) values ('H1', 20);
insert into tren (modelo, capacidad) values ('xD', 49);
insert into tren (modelo, capacidad) values ('300M', 45);
insert into tren (modelo, capacidad) values ('MKX', 46);
insert into tren (modelo, capacidad) values ('XC70', 23);
insert into tren (modelo, capacidad) values ('E-Class', 21);
insert into tren (modelo, capacidad) values ('Parisienne', 47);
insert into tren (modelo, capacidad) values ('525', 26);
insert into tren (modelo, capacidad) values ('G-Series 2500', 24);
insert into tren (modelo, capacidad) values ('F150', 23);
insert into tren (modelo, capacidad) values ('XC70', 46);
insert into tren (modelo, capacidad) values ('RSX', 35);
insert into tren (modelo, capacidad) values ('Reventón', 33);
insert into tren (modelo, capacidad) values ('Galant', 33);
insert into tren (modelo, capacidad) values ('S6', 26);
insert into tren (modelo, capacidad) values ('FJ Cruiser', 35);
insert into tren (modelo, capacidad) values ('8 Series', 27);
insert into tren (modelo, capacidad) values ('1500 Club Coupe', 48);
insert into tren (modelo, capacidad) values ('Hombre Space', 37);
insert into tren (modelo, capacidad) values ('ES', 25);
insert into tren (modelo, capacidad) values ('Windstar', 43);
insert into tren (modelo, capacidad) values ('2500', 39);
insert into tren (modelo, capacidad) values ('Corvette', 28);
insert into tren (modelo, capacidad) values ('E-Series', 37);
insert into tren (modelo, capacidad) values ('Sunbird', 41);
insert into tren (modelo, capacidad) values ('Sierra 2500', 38);
insert into tren (modelo, capacidad) values ('LX', 33);
insert into tren (modelo, capacidad) values ('Taurus', 40);
insert into tren (modelo, capacidad) values ('CTS', 40);
insert into tren (modelo, capacidad) values ('Astro', 46);
insert into tren (modelo, capacidad) values ('Mazda5', 32);
insert into tren (modelo, capacidad) values ('9000', 31);
insert into tren (modelo, capacidad) values ('5 Series', 22);
insert into tren (modelo, capacidad) values ('9000', 21);
insert into tren (modelo, capacidad) values ('900', 22);
insert into tren (modelo, capacidad) values ('Cayenne', 45);
insert into tren (modelo, capacidad) values ('Pajero', 46);
insert into tren (modelo, capacidad) values ('3500', 46);
insert into tren (modelo, capacidad) values ('Escort', 29);
insert into tren (modelo, capacidad) values ('S2000', 38);
insert into tren (modelo, capacidad) values ('E250', 31);
insert into tren (modelo, capacidad) values ('Galant', 23);
insert into tren (modelo, capacidad) values ('Century', 20);
insert into tren (modelo, capacidad) values ('D250', 33);
insert into tren (modelo, capacidad) values ('XJ Series', 28);
insert into tren (modelo, capacidad) values ('RX', 35);
insert into tren (modelo, capacidad) values ('Ram 1500', 46);
insert into tren (modelo, capacidad) values ('F-Series', 48);
insert into tren (modelo, capacidad) values ('X-Type', 35);
insert into tren (modelo, capacidad) values ('SLK-Class', 21);
insert into tren (modelo, capacidad) values ('Laser', 21);
insert into tren (modelo, capacidad) values ('SLR McLaren', 40);
insert into tren (modelo, capacidad) values ('5 Series', 45);
insert into tren (modelo, capacidad) values ('Explorer', 30);
insert into tren (modelo, capacidad) values ('Paseo', 21);
insert into tren (modelo, capacidad) values ('X3', 45);
insert into tren (modelo, capacidad) values ('E-Series', 29);
insert into tren (modelo, capacidad) values ('Suburban 2500', 37);
insert into tren (modelo, capacidad) values ('Accord', 35);
insert into tren (modelo, capacidad) values ('Tahoe', 38);
insert into tren (modelo, capacidad) values ('Xtra', 40);
insert into tren (modelo, capacidad) values ('Voyager', 23);
insert into tren (modelo, capacidad) values ('Discovery', 26);
insert into tren (modelo, capacidad) values ('Canyon', 41);
insert into tren (modelo, capacidad) values ('Azera', 33);
insert into tren (modelo, capacidad) values ('Wrangler', 47);
insert into tren (modelo, capacidad) values ('Corrado', 43);
insert into tren (modelo, capacidad) values ('Tempest', 38);
insert into tren (modelo, capacidad) values ('Golf', 27);
insert into tren (modelo, capacidad) values ('Reno', 24);
insert into tren (modelo, capacidad) values ('Firebird Formula', 41);
insert into tren (modelo, capacidad) values ('Sportage', 23);
insert into tren (modelo, capacidad) values ('F150', 48);
insert into tren (modelo, capacidad) values ('Montego', 43);
insert into tren (modelo, capacidad) values ('Miata MX-5', 38);
insert into tren (modelo, capacidad) values ('Sportage', 21);
insert into tren (modelo, capacidad) values ('Silverado 2500', 28);
insert into tren (modelo, capacidad) values ('SLK-Class', 21);
insert into tren (modelo, capacidad) values ('G25', 36);
insert into tren (modelo, capacidad) values ('SM', 32);
insert into tren (modelo, capacidad) values ('I', 34);
insert into tren (modelo, capacidad) values ('GX', 26);
insert into tren (modelo, capacidad) values ('599 GTB Fiorano', 44);
insert into tren (modelo, capacidad) values ('7 Series', 31);
insert into tren (modelo, capacidad) values ('Aerio', 35);
insert into tren (modelo, capacidad) values ('LR4', 49);
insert into tren (modelo, capacidad) values ('Tacoma', 41);
insert into tren (modelo, capacidad) values ('5000S', 20);
insert into tren (modelo, capacidad) values ('QX56', 32);
insert into tren (modelo, capacidad) values ('Space', 49);
insert into tren (modelo, capacidad) values ('Viper', 50);
insert into tren (modelo, capacidad) values ('Mariner', 48);
insert into tren (modelo, capacidad) values ('F250', 38);
insert into tren (modelo, capacidad) values ('Xtra', 47);
insert into tren (modelo, capacidad) values ('LeSabre', 30);
insert into tren (modelo, capacidad) values ('GL-Class', 41);
insert into tren (modelo, capacidad) values ('Miata MX-5', 20);
insert into tren (modelo, capacidad) values ('Cooper Countryman', 29);
insert into tren (modelo, capacidad) values ('Grand Vitara', 48);
insert into tren (modelo, capacidad) values ('Toronado', 28);
insert into tren (modelo, capacidad) values ('Ram Van 2500', 25);
insert into tren (modelo, capacidad) values ('545', 46);
insert into tren (modelo, capacidad) values ('Grand Prix', 47);
insert into tren (modelo, capacidad) values ('Odyssey', 45);
insert into tren (modelo, capacidad) values ('Mazda3', 30);
insert into tren (modelo, capacidad) values ('Odyssey', 33);
insert into tren (modelo, capacidad) values ('Axiom', 22);
insert into tren (modelo, capacidad) values ('Quattroporte', 44);
insert into tren (modelo, capacidad) values ('S-Class', 49);
insert into tren (modelo, capacidad) values ('Pacifica', 28);
insert into tren (modelo, capacidad) values ('Jimmy', 21);
insert into tren (modelo, capacidad) values ('Silverado 2500', 22);
insert into tren (modelo, capacidad) values ('Caprice Classic', 33);
insert into tren (modelo, capacidad) values ('Econoline E350', 41);
insert into tren (modelo, capacidad) values ('Colt Vista', 45);
insert into tren (modelo, capacidad) values ('Sonata', 50);
insert into tren (modelo, capacidad) values ('Astro', 25);
insert into tren (modelo, capacidad) values ('Panamera', 44);
insert into tren (modelo, capacidad) values ('Ram 3500 Club', 46);
insert into tren (modelo, capacidad) values ('240SX', 50);
insert into tren (modelo, capacidad) values ('E250', 33);
insert into tren (modelo, capacidad) values ('525', 26);
insert into tren (modelo, capacidad) values ('LS', 40);
insert into tren (modelo, capacidad) values ('Envoy', 46);
insert into tren (modelo, capacidad) values ('Cabriolet', 27);
insert into tren (modelo, capacidad) values ('Riviera', 41);
insert into tren (modelo, capacidad) values ('Fusion', 23);
insert into tren (modelo, capacidad) values ('i-290', 24);
insert into tren (modelo, capacidad) values ('Challenger', 43);
insert into tren (modelo, capacidad) values ('940', 47);
insert into tren (modelo, capacidad) values ('M-Class', 22);
insert into tren (modelo, capacidad) values ('Golf', 50);
insert into tren (modelo, capacidad) values ('FX', 46);
insert into tren (modelo, capacidad) values ('Liberty', 50);
insert into tren (modelo, capacidad) values ('GL-Class', 26);
insert into tren (modelo, capacidad) values ('Ram 3500', 47);
insert into tren (modelo, capacidad) values ('ES', 45);
insert into tren (modelo, capacidad) values ('S6', 29);
insert into tren (modelo, capacidad) values ('Echo', 49);
insert into tren (modelo, capacidad) values ('Mini Cooper S', 29);
insert into tren (modelo, capacidad) values ('Trooper', 47);
insert into tren (modelo, capacidad) values ('S4', 40);
insert into tren (modelo, capacidad) values ('CTS-V', 33);
insert into tren (modelo, capacidad) values ('LS', 46);
insert into tren (modelo, capacidad) values ('S-Class', 23);
insert into tren (modelo, capacidad) values ('GTO', 50);
insert into tren (modelo, capacidad) values ('Grand Vitara', 27);
insert into tren (modelo, capacidad) values ('Tiguan', 25);
insert into tren (modelo, capacidad) values ('S40', 33);
insert into tren (modelo, capacidad) values ('940', 42);
insert into tren (modelo, capacidad) values ('X6', 36);
insert into tren (modelo, capacidad) values ('Grand Prix', 23);
insert into tren (modelo, capacidad) values ('Quattroporte', 24);
insert into tren (modelo, capacidad) values ('300ZX', 30);
insert into tren (modelo, capacidad) values ('Express', 32);
insert into tren (modelo, capacidad) values ('8 Series', 22);
insert into tren (modelo, capacidad) values ('Express 3500', 20);
insert into tren (modelo, capacidad) values ('Five Hundred', 20);
insert into tren (modelo, capacidad) values ('Mustang', 36);
insert into tren (modelo, capacidad) values ('CLS-Class', 27);
insert into tren (modelo, capacidad) values ('Trooper', 39);
insert into tren (modelo, capacidad) values ('i-Series', 47);
insert into tren (modelo, capacidad) values ('Tracer', 48);
insert into tren (modelo, capacidad) values ('Familia', 46);
insert into tren (modelo, capacidad) values ('Wrangler', 34);
insert into tren (modelo, capacidad) values ('500SEL', 26);
insert into tren (modelo, capacidad) values ('Quest', 24);
insert into tren (modelo, capacidad) values ('Sierra 3500', 34);
insert into tren (modelo, capacidad) values ('Topaz', 44);
insert into tren (modelo, capacidad) values ('DBS', 30);
insert into tren (modelo, capacidad) values ('Galant', 36);
insert into tren (modelo, capacidad) values ('LR4', 26);
insert into tren (modelo, capacidad) values ('Express 2500', 45);
insert into tren (modelo, capacidad) values ('S60', 45);
insert into tren (modelo, capacidad) values ('Sierra 1500', 45);
insert into tren (modelo, capacidad) values ('Type 2', 41);
insert into tren (modelo, capacidad) values ('Impreza', 30);
insert into tren (modelo, capacidad) values ('Torrent', 25);
insert into tren (modelo, capacidad) values ('2500', 48);
insert into tren (modelo, capacidad) values ('Mazda3', 27);
insert into tren (modelo, capacidad) values ('Passat', 32);
insert into tren (modelo, capacidad) values ('Cayenne', 21);
insert into tren (modelo, capacidad) values ('3500', 44);
insert into tren (modelo, capacidad) values ('Colt Vista', 31);
insert into tren (modelo, capacidad) values ('Trooper', 49);
insert into tren (modelo, capacidad) values ('E-Series', 44);
insert into tren (modelo, capacidad) values ('Thunderbird', 21);
insert into tren (modelo, capacidad) values ('Liberty', 20);
insert into tren (modelo, capacidad) values ('Volt', 50);
insert into tren (modelo, capacidad) values ('CTS', 24);
insert into tren (modelo, capacidad) values ('Lumina', 50);
insert into tren (modelo, capacidad) values ('Z4 M', 44);
insert into tren (modelo, capacidad) values ('SJ', 50);
insert into tren (modelo, capacidad) values ('Flex', 22);
insert into tren (modelo, capacidad) values ('Gemini', 24);
insert into tren (modelo, capacidad) values ('4Runner', 43);
insert into tren (modelo, capacidad) values ('Corvette', 20);
insert into tren (modelo, capacidad) values ('Ram 3500', 24);
insert into tren (modelo, capacidad) values ('Sonata', 21);
insert into tren (modelo, capacidad) values ('rio', 48);
insert into tren (modelo, capacidad) values ('Rally Wagon G3500', 43);
insert into tren (modelo, capacidad) values ('Express 1500', 23);
insert into tren (modelo, capacidad) values ('MX-6', 47);
insert into tren (modelo, capacidad) values ('RS 6', 21);
insert into tren (modelo, capacidad) values ('Forester', 34);
insert into tren (modelo, capacidad) values ('900', 40);
insert into tren (modelo, capacidad) values ('Cooper', 42);
insert into tren (modelo, capacidad) values ('Pilot', 25);
insert into tren (modelo, capacidad) values ('Taurus', 34);
insert into tren (modelo, capacidad) values ('Protege5', 24);
insert into tren (modelo, capacidad) values ('Toronado', 35);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 28);
insert into tren (modelo, capacidad) values ('Mountaineer', 42);
insert into tren (modelo, capacidad) values ('Element', 49);
insert into tren (modelo, capacidad) values ('300E', 32);
insert into tren (modelo, capacidad) values ('Aerostar', 45);
insert into tren (modelo, capacidad) values ('Pilot', 39);
insert into tren (modelo, capacidad) values ('300SL', 28);
insert into tren (modelo, capacidad) values ('Passat', 45);
insert into tren (modelo, capacidad) values ('E-Class', 21);
insert into tren (modelo, capacidad) values ('J', 39);
insert into tren (modelo, capacidad) values ('Suburban', 25);
insert into tren (modelo, capacidad) values ('300CE', 45);
insert into tren (modelo, capacidad) values ('Legacy', 43);
insert into tren (modelo, capacidad) values ('Grand Voyager', 50);
insert into tren (modelo, capacidad) values ('7 Series', 47);
insert into tren (modelo, capacidad) values ('RX-7', 22);
insert into tren (modelo, capacidad) values ('Topaz', 40);
insert into tren (modelo, capacidad) values ('Grand Prix', 21);
insert into tren (modelo, capacidad) values ('F-Series', 21);
insert into tren (modelo, capacidad) values ('Sable', 48);
insert into tren (modelo, capacidad) values ('Compass', 42);
insert into tren (modelo, capacidad) values ('Forester', 45);
insert into tren (modelo, capacidad) values ('Range Rover', 48);
insert into tren (modelo, capacidad) values ('G', 41);
insert into tren (modelo, capacidad) values ('MX-5', 47);
insert into tren (modelo, capacidad) values ('Element', 50);
insert into tren (modelo, capacidad) values ('Range Rover Sport', 21);
insert into tren (modelo, capacidad) values ('A3', 24);
insert into tren (modelo, capacidad) values ('FX', 47);
insert into tren (modelo, capacidad) values ('9-5', 28);
insert into tren (modelo, capacidad) values ('Golf', 23);
insert into tren (modelo, capacidad) values ('Cayman', 35);
insert into tren (modelo, capacidad) values ('SLX', 28);
insert into tren (modelo, capacidad) values ('XK Series', 34);
insert into tren (modelo, capacidad) values ('3500', 30);
insert into tren (modelo, capacidad) values ('Genesis', 36);
insert into tren (modelo, capacidad) values ('Riviera', 30);
insert into tren (modelo, capacidad) values ('Cayenne', 48);
insert into tren (modelo, capacidad) values ('Ram Van 3500', 41);
insert into tren (modelo, capacidad) values ('Silverado 2500', 30);
insert into tren (modelo, capacidad) values ('Ram 3500', 28);
insert into tren (modelo, capacidad) values ('Grand Vitara', 50);
insert into tren (modelo, capacidad) values ('Mustang', 42);
insert into tren (modelo, capacidad) values ('Ranger', 21);
insert into tren (modelo, capacidad) values ('7 Series', 20);
insert into tren (modelo, capacidad) values ('Voyager', 20);
insert into tren (modelo, capacidad) values ('Imperial', 32);
insert into tren (modelo, capacidad) values ('Reno', 35);
insert into tren (modelo, capacidad) values ('S-Class', 38);
insert into tren (modelo, capacidad) values ('Gemini', 27);
insert into tren (modelo, capacidad) values ('VUE', 28);
insert into tren (modelo, capacidad) values ('MKS', 20);
insert into tren (modelo, capacidad) values ('GL-Class', 39);
insert into tren (modelo, capacidad) values ('M-Class', 25);
insert into tren (modelo, capacidad) values ('M', 20);
insert into tren (modelo, capacidad) values ('Elantra', 46);
insert into tren (modelo, capacidad) values ('NSX', 33);
insert into tren (modelo, capacidad) values ('Murano', 48);
insert into tren (modelo, capacidad) values ('G5', 39);
insert into tren (modelo, capacidad) values ('GT', 20);
insert into tren (modelo, capacidad) values ('Equinox', 50);
insert into tren (modelo, capacidad) values ('Cube', 44);
insert into tren (modelo, capacidad) values ('Intrigue', 39);
insert into tren (modelo, capacidad) values ('Spyder', 23);
insert into tren (modelo, capacidad) values ('TT', 23);
insert into tren (modelo, capacidad) values ('Continental', 21);
insert into tren (modelo, capacidad) values ('Rodeo Sport', 21);
insert into tren (modelo, capacidad) values ('Ram Van 3500', 35);
insert into tren (modelo, capacidad) values ('Grand Cherokee', 47);
insert into tren (modelo, capacidad) values ('LaCrosse', 33);
insert into tren (modelo, capacidad) values ('Celica', 42);
insert into tren (modelo, capacidad) values ('Vigor', 40);
insert into tren (modelo, capacidad) values ('Grand Am', 46);
insert into tren (modelo, capacidad) values ('Sentra', 26);
insert into tren (modelo, capacidad) values ('Santa Fe', 27);
insert into tren (modelo, capacidad) values ('Celica', 36);
insert into tren (modelo, capacidad) values ('Passat', 26);
insert into tren (modelo, capacidad) values ('E150', 28);
insert into tren (modelo, capacidad) values ('Lancer', 20);
insert into tren (modelo, capacidad) values ('Navigator L', 41);
insert into tren (modelo, capacidad) values ('Tempo', 35);
insert into tren (modelo, capacidad) values ('Continental Mark VII', 23);
insert into tren (modelo, capacidad) values ('Titan', 25);
insert into tren (modelo, capacidad) values ('Silverado 3500HD', 28);
insert into tren (modelo, capacidad) values ('Grand Prix', 47);
insert into tren (modelo, capacidad) values ('S60', 22);
insert into tren (modelo, capacidad) values ('E-Series', 50);
insert into tren (modelo, capacidad) values ('Sequoia', 41);
insert into tren (modelo, capacidad) values ('F-Series', 37);
insert into tren (modelo, capacidad) values ('Sierra', 21);
insert into tren (modelo, capacidad) values ('Azure', 41);
insert into tren (modelo, capacidad) values ('V40', 25);
insert into tren (modelo, capacidad) values ('Cruze', 24);
insert into tren (modelo, capacidad) values ('Elise', 45);
insert into tren (modelo, capacidad) values ('Electra', 36);
insert into tren (modelo, capacidad) values ('R8', 48);
insert into tren (modelo, capacidad) values ('Cabriolet', 20);
insert into tren (modelo, capacidad) values ('CLK-Class', 34);
insert into tren (modelo, capacidad) values ('Mark LT', 45);
insert into tren (modelo, capacidad) values ('Mustang', 25);
insert into tren (modelo, capacidad) values ('SL-Class', 22);
insert into tren (modelo, capacidad) values ('Swift', 31);
insert into tren (modelo, capacidad) values ('5 Series', 46);
insert into tren (modelo, capacidad) values ('Discovery', 30);
insert into tren (modelo, capacidad) values ('760', 33);
insert into tren (modelo, capacidad) values ('Tundra', 23);
insert into tren (modelo, capacidad) values ('4Runner', 22);
insert into tren (modelo, capacidad) values ('Prowler', 31);
insert into tren (modelo, capacidad) values ('RX-8', 40);
insert into tren (modelo, capacidad) values ('626', 36);
insert into tren (modelo, capacidad) values ('A6', 26);
insert into tren (modelo, capacidad) values ('Tracker', 48);
insert into tren (modelo, capacidad) values ('Mustang', 28);
insert into tren (modelo, capacidad) values ('Sorento', 37);
insert into tren (modelo, capacidad) values ('Taurus', 40);
insert into tren (modelo, capacidad) values ('SL-Class', 39);
insert into tren (modelo, capacidad) values ('Tribeca', 48);
insert into tren (modelo, capacidad) values ('Impala', 36);
insert into tren (modelo, capacidad) values ('Impala', 47);
insert into tren (modelo, capacidad) values ('8 Series', 35);
insert into tren (modelo, capacidad) values ('Cavalier', 20);
insert into tren (modelo, capacidad) values ('Sebring', 29);
insert into tren (modelo, capacidad) values ('S6', 30);
insert into tren (modelo, capacidad) values ('G-Series G20', 21);
insert into tren (modelo, capacidad) values ('Viper', 24);
insert into tren (modelo, capacidad) values ('SVX', 32);
insert into tren (modelo, capacidad) values ('Ram Van 1500', 50);
insert into tren (modelo, capacidad) values ('RL', 46);
insert into tren (modelo, capacidad) values ('3000GT', 46);
insert into tren (modelo, capacidad) values ('F-Series', 34);
insert into tren (modelo, capacidad) values ('Cabriolet', 36);
insert into tren (modelo, capacidad) values ('MPV', 38);
insert into tren (modelo, capacidad) values ('D150', 38);
insert into tren (modelo, capacidad) values ('X6', 40);
insert into tren (modelo, capacidad) values ('E-Class', 22);
insert into tren (modelo, capacidad) values ('F150', 42);
insert into tren (modelo, capacidad) values ('300', 48);
insert into tren (modelo, capacidad) values ('Firefly', 48);
insert into tren (modelo, capacidad) values ('Colorado', 21);
insert into tren (modelo, capacidad) values ('F350', 39);
insert into tren (modelo, capacidad) values ('CX-7', 32);
insert into tren (modelo, capacidad) values ('Skyhawk', 47);
insert into tren (modelo, capacidad) values ('GS', 30);
insert into tren (modelo, capacidad) values ('Cougar', 31);
insert into tren (modelo, capacidad) values ('Tundra', 40);
insert into tren (modelo, capacidad) values ('STS', 46);
insert into tren (modelo, capacidad) values ('Millenia', 29);
insert into tren (modelo, capacidad) values ('400SE', 27);
insert into tren (modelo, capacidad) values ('E350', 49);
insert into tren (modelo, capacidad) values ('A4', 49);
insert into tren (modelo, capacidad) values ('Brooklands', 21);
insert into tren (modelo, capacidad) values ('RX', 37);
insert into tren (modelo, capacidad) values ('Dakota', 23);
insert into tren (modelo, capacidad) values ('A6', 37);
insert into tren (modelo, capacidad) values ('Entourage', 48);
insert into tren (modelo, capacidad) values ('Jetta', 41);
insert into tren (modelo, capacidad) values ('Ram Van 1500', 49);
insert into tren (modelo, capacidad) values ('Celica', 37);
insert into tren (modelo, capacidad) values ('Ranger', 46);
insert into tren (modelo, capacidad) values ('Galant', 46);
insert into tren (modelo, capacidad) values ('RDX', 20);
insert into tren (modelo, capacidad) values ('Altima', 43);
insert into tren (modelo, capacidad) values ('LS', 28);
insert into tren (modelo, capacidad) values ('Regal', 38);
insert into tren (modelo, capacidad) values ('LeSabre', 32);
insert into tren (modelo, capacidad) values ('Tahoe', 33);
insert into tren (modelo, capacidad) values ('RAV4', 26);
insert into tren (modelo, capacidad) values ('Town & Country', 29);
insert into tren (modelo, capacidad) values ('Vitara', 32);
insert into tren (modelo, capacidad) values ('Villager', 39);
insert into tren (modelo, capacidad) values ('Civic', 46);
insert into tren (modelo, capacidad) values ('S80', 24);
insert into tren (modelo, capacidad) values ('S4', 22);
insert into tren (modelo, capacidad) values ('Sierra 1500', 45);
insert into tren (modelo, capacidad) values ('Ram Van 2500', 22);
insert into tren (modelo, capacidad) values ('GTO', 20);
insert into tren (modelo, capacidad) values ('944', 25);
insert into tren (modelo, capacidad) values ('Legacy', 21);
insert into tren (modelo, capacidad) values ('SLR McLaren', 25);
insert into tren (modelo, capacidad) values ('LeMans', 40);
insert into tren (modelo, capacidad) values ('Diamante', 23);
insert into tren (modelo, capacidad) values ('Alliance', 47);
insert into tren (modelo, capacidad) values ('Echo', 43);
insert into tren (modelo, capacidad) values ('Sentra', 49);
insert into tren (modelo, capacidad) values ('Familia', 35);
insert into tren (modelo, capacidad) values ('Suburban 2500', 50);
insert into tren (modelo, capacidad) values ('Aveo', 22);
insert into tren (modelo, capacidad) values ('TT', 43);
insert into tren (modelo, capacidad) values ('Fit', 27);
insert into tren (modelo, capacidad) values ('Trooper', 41);
insert into tren (modelo, capacidad) values ('GTI', 26);
insert into tren (modelo, capacidad) values ('G-Series 1500', 42);
insert into tren (modelo, capacidad) values ('Dakota Club', 46);
insert into tren (modelo, capacidad) values ('Corvette', 46);
insert into tren (modelo, capacidad) values ('RX', 38);
insert into tren (modelo, capacidad) values ('Golf', 26);
insert into tren (modelo, capacidad) values ('F250', 50);
insert into tren (modelo, capacidad) values ('G-Class', 23);
insert into tren (modelo, capacidad) values ('Accord', 46);
insert into tren (modelo, capacidad) values ('CLK-Class', 24);
insert into tren (modelo, capacidad) values ('LaCrosse', 38);
insert into tren (modelo, capacidad) values ('E250', 30);
insert into tren (modelo, capacidad) values ('DeVille', 27);
insert into tren (modelo, capacidad) values ('Cutlass Supreme', 50);
insert into tren (modelo, capacidad) values ('Corolla', 23);
insert into tren (modelo, capacidad) values ('Jetta', 38);
insert into tren (modelo, capacidad) values ('Tracker', 22);
insert into tren (modelo, capacidad) values ('Aztek', 21);
insert into tren (modelo, capacidad) values ('Rondo', 36);
insert into tren (modelo, capacidad) values ('Arnage', 50);
insert into tren (modelo, capacidad) values ('525', 32);
insert into tren (modelo, capacidad) values ('Firefly', 27);
insert into tren (modelo, capacidad) values ('Taurus', 47);
insert into tren (modelo, capacidad) values ('Esprit', 46);
insert into tren (modelo, capacidad) values ('Continental Mark VII', 30);
insert into tren (modelo, capacidad) values ('5 Series', 43);
insert into tren (modelo, capacidad) values ('G-Series 1500', 50);
insert into tren (modelo, capacidad) values ('Sidekick', 27);
insert into tren (modelo, capacidad) values ('S8', 47);
insert into tren (modelo, capacidad) values ('Prelude', 38);
insert into tren (modelo, capacidad) values ('Sunfire', 40);
insert into tren (modelo, capacidad) values ('Eldorado', 26);
insert into tren (modelo, capacidad) values ('Outlander', 38);
insert into tren (modelo, capacidad) values ('Carrera GT', 38);
insert into tren (modelo, capacidad) values ('Grand Marquis', 22);
insert into tren (modelo, capacidad) values ('Altima', 20);
insert into tren (modelo, capacidad) values ('SRX', 36);
insert into tren (modelo, capacidad) values ('Malibu', 32);
insert into tren (modelo, capacidad) values ('Navigator', 35);
insert into tren (modelo, capacidad) values ('Caprice', 37);
insert into tren (modelo, capacidad) values ('5 Series', 41);
insert into tren (modelo, capacidad) values ('Ramcharger', 22);
insert into tren (modelo, capacidad) values ('MR2', 46);
insert into tren (modelo, capacidad) values ('Festiva', 38);
insert into tren (modelo, capacidad) values ('G6', 36);
insert into tren (modelo, capacidad) values ('Uplander', 25);
insert into tren (modelo, capacidad) values ('RL', 23);
insert into tren (modelo, capacidad) values ('Rio', 34);
insert into tren (modelo, capacidad) values ('Skylark', 38);
insert into tren (modelo, capacidad) values ('Yukon', 40);
insert into tren (modelo, capacidad) values ('Park Avenue', 22);
insert into tren (modelo, capacidad) values ('Firebird', 21);
insert into tren (modelo, capacidad) values ('H2', 38);
insert into tren (modelo, capacidad) values ('Cavalier', 33);
insert into tren (modelo, capacidad) values ('9-3', 42);
insert into tren (modelo, capacidad) values ('Cherokee', 21);
insert into tren (modelo, capacidad) values ('M3', 42);
insert into tren (modelo, capacidad) values ('Gallardo', 36);
insert into tren (modelo, capacidad) values ('W201', 31);
insert into tren (modelo, capacidad) values ('Outback', 24);
insert into tren (modelo, capacidad) values ('Ranger', 35);
insert into tren (modelo, capacidad) values ('MDX', 45);
insert into tren (modelo, capacidad) values ('Leganza', 43);
insert into tren (modelo, capacidad) values ('Vitara', 37);
insert into tren (modelo, capacidad) values ('CLS-Class', 26);
insert into tren (modelo, capacidad) values ('LS', 36);
insert into tren (modelo, capacidad) values ('C-Class', 28);
insert into tren (modelo, capacidad) values ('Golf', 45);
insert into tren (modelo, capacidad) values ('850', 27);
insert into tren (modelo, capacidad) values ('S4', 34);
insert into tren (modelo, capacidad) values ('Mustang', 32);
insert into tren (modelo, capacidad) values ('Escalade ESV', 41);
insert into tren (modelo, capacidad) values ('Matrix', 23);
insert into tren (modelo, capacidad) values ('Mustang', 41);
insert into tren (modelo, capacidad) values ('Z8', 32);
insert into tren (modelo, capacidad) values ('Safari', 36);
insert into tren (modelo, capacidad) values ('Rendezvous', 28);
insert into tren (modelo, capacidad) values ('Tracker', 25);
insert into tren (modelo, capacidad) values ('MR2', 46);
insert into tren (modelo, capacidad) values ('A4', 39);
insert into tren (modelo, capacidad) values ('SLX', 31);
insert into tren (modelo, capacidad) values ('6 Series', 22);
insert into tren (modelo, capacidad) values ('M6', 44);
insert into tren (modelo, capacidad) values ('Viper', 43);
insert into tren (modelo, capacidad) values ('A3', 31);
insert into tren (modelo, capacidad) values ('Passat', 42);
insert into tren (modelo, capacidad) values ('4Runner', 33);
insert into tren (modelo, capacidad) values ('Silhouette', 33);
insert into tren (modelo, capacidad) values ('GTO', 43);
insert into tren (modelo, capacidad) values ('Equinox', 36);
insert into tren (modelo, capacidad) values ('C70', 32);
insert into tren (modelo, capacidad) values ('500SL', 41);
insert into tren (modelo, capacidad) values ('I', 45);
insert into tren (modelo, capacidad) values ('Diamante', 38);
insert into tren (modelo, capacidad) values ('Equator', 42);
insert into tren (modelo, capacidad) values ('Accord', 21);
insert into tren (modelo, capacidad) values ('SLS-Class', 25);
insert into tren (modelo, capacidad) values ('Grand Marquis', 33);
insert into tren (modelo, capacidad) values ('Taurus X', 21);
insert into tren (modelo, capacidad) values ('Silverado 1500', 49);
insert into tren (modelo, capacidad) values ('Tahoe', 45);
insert into tren (modelo, capacidad) values ('Highlander', 48);
insert into tren (modelo, capacidad) values ('LTD Crown Victoria', 44);
insert into tren (modelo, capacidad) values ('Riviera', 27);
insert into tren (modelo, capacidad) values ('Santa Fe', 23);
insert into tren (modelo, capacidad) values ('Miata MX-5', 40);
insert into tren (modelo, capacidad) values ('E-Series', 24);
insert into tren (modelo, capacidad) values ('Thunderbird', 47);
